name: .NET Core CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore DemoApp/DemoApp.csproj
    - name: Build
      run: dotnet build DemoApp/DemoApp.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore DemoApp/DemoApp.csproj

    - name: Build
      run: dotnet build DemoApp/DemoApp.csproj --no-restore

    - name: Publish
      run: dotnet publish DemoApp/DemoApp.csproj --no-build --output ./publish

    # Add your deployment steps here