name: 'Bicep Whatif / Deploy'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
    bicep-deploy:
        name: 'Bicep Deploy'
        #TODO can we easily determine if there are any changes to deploy?
        if: github.ref == 'refs/heads/main' 
        runs-on: ubuntu-latest
    
        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
        # Authenticate to Az CLI using OIDC
        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        # Deploy
        - name: "Bicep Deployment"
          uses: Azure/cli@v1
          with:
            inlineScript: |
                az deployment group create \
                --name deploy-${{ github.run_id }} \
                --resource-group rg-gab-auckland-demo \
                --template-file Infra\infra.bicep 